# Use postgres/postgres user/password credentials
version: "3.1"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - elixir
  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080
    networks:
      - elixir
  app:
    image: registry.mcd.com/bmcclure89/elixirdemo:latest
    ports:
      - 4000:4000
    networks:
      - elixir
  app02:
    image: registry.mcd.com/bmcclure89/elixirdemo:latest
    environment:
      - elixir_PORT=4000
    ports:
      - 4001:4000
    networks:
      - elixir
networks:
  elixir:
    driver: overlay
    attachable: true